#!/bin/sh

script_dir=$(dirname $(readlink -f $0))

object=$1; shift
source=$1; shift

echo "$source" | grep '^/' > /dev/null
if [ ! $? -eq 0 ]
then
    source="`pwd`/$source"
fi

tool=$script_dir/kernel_cc

cmd="$tool -c -MMD -MP $kernel_flags -o $object $source $*"
echo $cmd > $object.cmd
exec $cmd
