
include ../mk/pre.makefile

package_name = utl

package_dynamic_link_flags = -lpthread

cpp_sources = \
	exception.cpp \
	string_buffer.cpp \
	string_tokenizer.cpp \
	thread.cpp \
	spin_lock.cpp \
	os_utils.cpp \

include ../mk/post.makefile
